### ISSUE TITLE
Promote Winglang + React Workshop

### ISSUE THREAD

**Issue by dannac2** [winglang/gtm#395]
Event link: https://www.eventbrite.com/e/winglang-react-workshop-tickets-754616256537?aff=oddtdtcreator

- [x] linkedin
- [x] twitter
- [x] slack
- [x] invitation email in hubspot
- [ ] upload all sign ups to HS (from eventbrite)
- [ ] send follow up email
```[tasklist]
### Tasks
- [ ] Remind people before through Eventbrite
```
